import Navbar from "@/components/navbar";
import "./globals.css";
import Footer from "@/components/footer";
import NextTopLoader from 'nextjs-toploader';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return ( 
    <html lang="en">
      <body
        className="bg-white text-gray-600 work-sans leading-normal text-base tracking-normal"
      >
         <NextTopLoader color="#000"/>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
    
  );
}
